// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelData, CancelErrors, CancelResponses, CreateHoldData, CreateHoldErrors, CreateHoldResponses, CreateSnapshotData, CreateSnapshotErrors, CreateSnapshotResponses, DestroyPeerSnapshotData, DestroyPeerSnapshotErrors, DestroyPeerSnapshotResponses, DestroySnapshotData, DestroySnapshotErrors, DestroySnapshotResponses, GetArcData, GetArcErrors, GetArcHistoryData, GetArcHistoryResponses, GetArcResponses, GetConfigData, GetConfigErrors, GetConfigResponses, GetPeerJobData, GetPeerJobErrors, GetPeerJobResponses, GetPoolData, GetPoolErrors, GetPoolResponses, ListDatasetsData, ListDatasetsErrors, ListDatasetsResponses, ListHoldsData, ListHoldsErrors, ListHoldsResponses, ListJobsData, ListJobsResponses, ListPeerDatasetsData, ListPeerDatasetsErrors, ListPeerDatasetsResponses, ListPeerJobsData, ListPeerJobsErrors, ListPeerJobsResponses, ListPeersData, ListPeerSnapshotsData, ListPeerSnapshotsErrors, ListPeerSnapshotsResponses, ListPeersResponses, ListPoolsData, ListPoolsErrors, ListPoolsResponses, ListRunsData, ListRunsResponses, ListSnapshotsData, ListSnapshotsErrors, ListSnapshotsResponses, PauseData, PauseErrors, PauseResponses, PoolScrubData, PoolScrubErrors, PoolScrubResponses, PushToPeerData, PushToPeerErrors, PushToPeerResponses, ReleaseHoldData, ReleaseHoldErrors, ReleaseHoldResponses, ResumeData, ResumeErrors, ResumeResponses, StreamEventsData, StreamEventsResponses, StreamPeerEventsData, StreamPeerEventsErrors, StreamPeerEventsResponses, WakeupData, WakeupErrors, WakeupPeerJobData, WakeupPeerJobErrors, WakeupPeerJobResponses, WakeupResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getConfig = <ThrowOnError extends boolean = false>(options?: Options<GetConfigData, ThrowOnError>) => (options?.client ?? client).get<GetConfigResponses, GetConfigErrors, ThrowOnError>({ url: '/api/v1/config', ...options });

/**
 * List datasets reachable through the daemon's shared `CommandRunner`
 * (`AppState::runner`). RealRunner in production; SshCommandRunner
 * only when `PALIMPSEST_SSH_TARGET` is set for dev/test.
 */
export const listDatasets = <ThrowOnError extends boolean = false>(options?: Options<ListDatasetsData, ThrowOnError>) => (options?.client ?? client).get<ListDatasetsResponses, ListDatasetsErrors, ThrowOnError>({ url: '/api/v1/datasets', ...options });

/**
 * List snapshots of `{name}` (one dataset, non-recursive). Properties
 * `creation` and `used` come along so the UI can render age + size.
 */
export const listSnapshots = <ThrowOnError extends boolean = false>(options: Options<ListSnapshotsData, ThrowOnError>) => (options.client ?? client).get<ListSnapshotsResponses, ListSnapshotsErrors, ThrowOnError>({ url: '/api/v1/datasets/{name}/snapshots', ...options });

/**
 * Create a snapshot of `{name}` named `req.snapshot_name`.
 * `palimpsest::ZfsError::SnapshotExists` maps to 409 — the caller
 * decides whether already-exists is fatal.
 */
export const createSnapshot = <ThrowOnError extends boolean = false>(options: Options<CreateSnapshotData, ThrowOnError>) => (options.client ?? client).post<CreateSnapshotResponses, CreateSnapshotErrors, ThrowOnError>({
    url: '/api/v1/datasets/{name}/snapshots',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Destroy snapshot `{name}@{snapshot}`. Path-segment escaping: the
 * dataset goes URL-encoded (`%2F` for `/`); the snapshot tag is the
 * part after the `@`.
 */
export const destroySnapshot = <ThrowOnError extends boolean = false>(options: Options<DestroySnapshotData, ThrowOnError>) => (options.client ?? client).post<DestroySnapshotResponses, DestroySnapshotErrors, ThrowOnError>({ url: '/api/v1/datasets/{name}/snapshots/{snapshot}/destroy', ...options });

/**
 * `zfs holds <snapshot>` — list user holds blocking destroy. Empty
 * vec means the snapshot is destroy-eligible (as far as holds are
 * concerned; sub-clones still block independently).
 */
export const listHolds = <ThrowOnError extends boolean = false>(options: Options<ListHoldsData, ThrowOnError>) => (options.client ?? client).get<ListHoldsResponses, ListHoldsErrors, ThrowOnError>({ url: '/api/v1/datasets/{name}/snapshots/{snapshot}/holds', ...options });

/**
 * Place a user hold on `{name}@{snapshot}`. Tags with the `arctern_`
 * prefix are refused — they'd collide with the replication machinery's
 * step/last holds and be swept or misread by it.
 */
export const createHold = <ThrowOnError extends boolean = false>(options: Options<CreateHoldData, ThrowOnError>) => (options.client ?? client).post<CreateHoldResponses, CreateHoldErrors, ThrowOnError>({
    url: '/api/v1/datasets/{name}/snapshots/{snapshot}/holds',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Release a user hold. `arctern_*` tags ARE allowed here — releasing
 * a stuck step hold from the UI is exactly the recovery path this
 * endpoint exists for.
 */
export const releaseHold = <ThrowOnError extends boolean = false>(options: Options<ReleaseHoldData, ThrowOnError>) => (options.client ?? client).delete<ReleaseHoldResponses, ReleaseHoldErrors, ThrowOnError>({ url: '/api/v1/datasets/{name}/snapshots/{snapshot}/holds/{tag}', ...options });

/**
 * Subscribe to the daemon's log-event broadcast and yield each as an
 * SSE frame, preceded by a replay of the most recent events so a
 * freshly opened page shows context instead of an empty feed until
 * something new happens.
 */
export const streamEvents = <ThrowOnError extends boolean = false>(options?: Options<StreamEventsData, ThrowOnError>) => (options?.client ?? client).get<StreamEventsResponses, unknown, ThrowOnError>({ url: '/api/v1/events', ...options });

export const listJobs = <ThrowOnError extends boolean = false>(options?: Options<ListJobsData, ThrowOnError>) => (options?.client ?? client).get<ListJobsResponses, unknown, ThrowOnError>({ url: '/api/v1/jobs', ...options });

export const cancel = <ThrowOnError extends boolean = false>(options: Options<CancelData, ThrowOnError>) => (options.client ?? client).post<CancelResponses, CancelErrors, ThrowOnError>({ url: '/api/v1/jobs/{name}/cancel', ...options });

export const pause = <ThrowOnError extends boolean = false>(options: Options<PauseData, ThrowOnError>) => (options.client ?? client).post<PauseResponses, PauseErrors, ThrowOnError>({ url: '/api/v1/jobs/{name}/pause', ...options });

export const pushToPeer = <ThrowOnError extends boolean = false>(options: Options<PushToPeerData, ThrowOnError>) => (options.client ?? client).post<PushToPeerResponses, PushToPeerErrors, ThrowOnError>({ url: '/api/v1/jobs/{name}/push/{peer}', ...options });

export const resume = <ThrowOnError extends boolean = false>(options: Options<ResumeData, ThrowOnError>) => (options.client ?? client).post<ResumeResponses, ResumeErrors, ThrowOnError>({ url: '/api/v1/jobs/{name}/resume', ...options });

export const listRuns = <ThrowOnError extends boolean = false>(options: Options<ListRunsData, ThrowOnError>) => (options.client ?? client).get<ListRunsResponses, unknown, ThrowOnError>({ url: '/api/v1/jobs/{name}/runs', ...options });

export const wakeup = <ThrowOnError extends boolean = false>(options: Options<WakeupData, ThrowOnError>) => (options.client ?? client).post<WakeupResponses, WakeupErrors, ThrowOnError>({ url: '/api/v1/jobs/{name}/wakeup', ...options });

export const listPeers = <ThrowOnError extends boolean = false>(options?: Options<ListPeersData, ThrowOnError>) => (options?.client ?? client).get<ListPeersResponses, unknown, ThrowOnError>({ url: '/api/v1/peers', ...options });

export const listPeerDatasets = <ThrowOnError extends boolean = false>(options: Options<ListPeerDatasetsData, ThrowOnError>) => (options.client ?? client).get<ListPeerDatasetsResponses, ListPeerDatasetsErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/datasets', ...options });

/**
 * `GET /api/v1/peers/{peer}/events` — proxied SSE. Sends
 * SubscribeEvents to the peer's control channel and yields each
 * pushed Event frame as an SSE frame.
 */
export const streamPeerEvents = <ThrowOnError extends boolean = false>(options: Options<StreamPeerEventsData, ThrowOnError>) => (options.client ?? client).get<StreamPeerEventsResponses, StreamPeerEventsErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/events', ...options });

export const listPeerJobs = <ThrowOnError extends boolean = false>(options: Options<ListPeerJobsData, ThrowOnError>) => (options.client ?? client).get<ListPeerJobsResponses, ListPeerJobsErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/jobs', ...options });

export const getPeerJob = <ThrowOnError extends boolean = false>(options: Options<GetPeerJobData, ThrowOnError>) => (options.client ?? client).get<GetPeerJobResponses, GetPeerJobErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/jobs/{name}', ...options });

export const wakeupPeerJob = <ThrowOnError extends boolean = false>(options: Options<WakeupPeerJobData, ThrowOnError>) => (options.client ?? client).post<WakeupPeerJobResponses, WakeupPeerJobErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/jobs/{name}/wakeup', ...options });

export const listPeerSnapshots = <ThrowOnError extends boolean = false>(options: Options<ListPeerSnapshotsData, ThrowOnError>) => (options.client ?? client).get<ListPeerSnapshotsResponses, ListPeerSnapshotsErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/snapshots', ...options });

export const destroyPeerSnapshot = <ThrowOnError extends boolean = false>(options: Options<DestroyPeerSnapshotData, ThrowOnError>) => (options.client ?? client).post<DestroyPeerSnapshotResponses, DestroyPeerSnapshotErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/snapshots/{name}/destroy', ...options });

export const listPools = <ThrowOnError extends boolean = false>(options?: Options<ListPoolsData, ThrowOnError>) => (options?.client ?? client).get<ListPoolsResponses, ListPoolsErrors, ThrowOnError>({ url: '/api/v1/pools', ...options });

export const getPool = <ThrowOnError extends boolean = false>(options: Options<GetPoolData, ThrowOnError>) => (options.client ?? client).get<GetPoolResponses, GetPoolErrors, ThrowOnError>({ url: '/api/v1/pools/{name}', ...options });

export const poolScrub = <ThrowOnError extends boolean = false>(options: Options<PoolScrubData, ThrowOnError>) => (options.client ?? client).post<PoolScrubResponses, PoolScrubErrors, ThrowOnError>({
    url: '/api/v1/pools/{name}/scrub',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getArc = <ThrowOnError extends boolean = false>(options?: Options<GetArcData, ThrowOnError>) => (options?.client ?? client).get<GetArcResponses, GetArcErrors, ThrowOnError>({ url: '/api/v1/system/arc', ...options });

export const getArcHistory = <ThrowOnError extends boolean = false>(options?: Options<GetArcHistoryData, ThrowOnError>) => (options?.client ?? client).get<GetArcHistoryResponses, unknown, ThrowOnError>({ url: '/api/v1/system/arc/history', ...options });
