// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateSnapshotData, CreateSnapshotErrors, CreateSnapshotResponses, DestroyPeerSnapshotData, DestroyPeerSnapshotErrors, DestroyPeerSnapshotResponses, GetPeerJobData, GetPeerJobErrors, GetPeerJobResponses, ListDatasetsData, ListDatasetsErrors, ListDatasetsResponses, ListJobsData, ListJobsResponses, ListPeerJobsData, ListPeerJobsErrors, ListPeerJobsResponses, ListPeersData, ListPeerSnapshotsData, ListPeerSnapshotsErrors, ListPeerSnapshotsResponses, ListPeersResponses, StreamEventsData, StreamEventsResponses, StreamPeerEventsData, StreamPeerEventsErrors, StreamPeerEventsResponses, WakeupData, WakeupErrors, WakeupPeerJobData, WakeupPeerJobErrors, WakeupPeerJobResponses, WakeupResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List datasets reachable through `palimpsest`'s SSH runner. The runner
 * is constructed per-request from `PALIMPSEST_SSH_TARGET` /
 * `PALIMPSEST_SSH_PASSWORD` — cheap, and avoids shared mutable state in
 * the daemon for this slice. A future slice may pool / reuse runners.
 */
export const listDatasets = <ThrowOnError extends boolean = false>(options?: Options<ListDatasetsData, ThrowOnError>) => (options?.client ?? client).get<ListDatasetsResponses, ListDatasetsErrors, ThrowOnError>({ url: '/api/v1/datasets', ...options });

/**
 * Create a snapshot of `{name}` named `req.snapshot_name`. After ZFS
 * confirms creation, a follow-up `zfs list -j` materializes the
 * `DatasetSummary` so callers do not need a second round-trip.
 *
 * `palimpsest::ZfsError::SnapshotExists` maps to 409 (not 200/201) — the
 * caller decides whether already-exists is fatal.
 */
export const createSnapshot = <ThrowOnError extends boolean = false>(options: Options<CreateSnapshotData, ThrowOnError>) => (options.client ?? client).post<CreateSnapshotResponses, CreateSnapshotErrors, ThrowOnError>({
    url: '/api/v1/datasets/{name}/snapshots',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Subscribe to the daemon's log-event broadcast and yield each as an
 * SSE frame. Backlog replay is intentionally out of scope for v1 — the
 * receiver-side SubscribeEvents handler is built around polling
 * log_events directly. UI clients that want history hit a
 * future `/api/v1/events?since=…` endpoint or the SQLite directly.
 */
export const streamEvents = <ThrowOnError extends boolean = false>(options?: Options<StreamEventsData, ThrowOnError>) => (options?.client ?? client).get<StreamEventsResponses, unknown, ThrowOnError>({ url: '/api/v1/events', ...options });

export const listJobs = <ThrowOnError extends boolean = false>(options?: Options<ListJobsData, ThrowOnError>) => (options?.client ?? client).get<ListJobsResponses, unknown, ThrowOnError>({ url: '/api/v1/jobs', ...options });

export const wakeup = <ThrowOnError extends boolean = false>(options: Options<WakeupData, ThrowOnError>) => (options.client ?? client).post<WakeupResponses, WakeupErrors, ThrowOnError>({ url: '/api/v1/jobs/{name}/wakeup', ...options });

export const listPeers = <ThrowOnError extends boolean = false>(options?: Options<ListPeersData, ThrowOnError>) => (options?.client ?? client).get<ListPeersResponses, unknown, ThrowOnError>({ url: '/api/v1/peers', ...options });

/**
 * `GET /api/v1/peers/{peer}/events` — proxied SSE. Sends
 * SubscribeEvents to the peer's control channel and yields each
 * pushed Event frame as an SSE frame.
 */
export const streamPeerEvents = <ThrowOnError extends boolean = false>(options: Options<StreamPeerEventsData, ThrowOnError>) => (options.client ?? client).get<StreamPeerEventsResponses, StreamPeerEventsErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/events', ...options });

export const listPeerJobs = <ThrowOnError extends boolean = false>(options: Options<ListPeerJobsData, ThrowOnError>) => (options.client ?? client).get<ListPeerJobsResponses, ListPeerJobsErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/jobs', ...options });

export const getPeerJob = <ThrowOnError extends boolean = false>(options: Options<GetPeerJobData, ThrowOnError>) => (options.client ?? client).get<GetPeerJobResponses, GetPeerJobErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/jobs/{name}', ...options });

export const wakeupPeerJob = <ThrowOnError extends boolean = false>(options: Options<WakeupPeerJobData, ThrowOnError>) => (options.client ?? client).post<WakeupPeerJobResponses, WakeupPeerJobErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/jobs/{name}/wakeup', ...options });

export const listPeerSnapshots = <ThrowOnError extends boolean = false>(options: Options<ListPeerSnapshotsData, ThrowOnError>) => (options.client ?? client).get<ListPeerSnapshotsResponses, ListPeerSnapshotsErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/snapshots', ...options });

export const destroyPeerSnapshot = <ThrowOnError extends boolean = false>(options: Options<DestroyPeerSnapshotData, ThrowOnError>) => (options.client ?? client).post<DestroyPeerSnapshotResponses, DestroyPeerSnapshotErrors, ThrowOnError>({ url: '/api/v1/peers/{peer}/snapshots/{name}/destroy', ...options });
