// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body shape for `4xx`/`5xx` responses from the daemon. `error` is a
 * short machine-readable category (`spawn`, `dataset_not_found`, …);
 * `message` is a human-readable description.
 */
export type ApiErrorBody = {
    error: string;
    message: string;
};

/**
 * One row of `GET /api/v1/system/arc/history`. Slim by design —
 * only the fields the dashboard chart consumes. Add more columns
 * (and migrate `arcstats_history`) when a future view needs them.
 */
export type ArcHistoryPoint = {
    /**
     * Unix seconds.
     */
    timestamp: number;
    size: number;
    c: number;
    hits: number;
    misses: number;
};

/**
 * `GET /api/v1/system/arc` — a typed echo of the kernel's
 * `/proc/spl/kstat/zfs/arcstats`, plus a precomputed hit_ratio
 * (NaN encoded as `null` for empty caches). Fields mirror the
 * palimpsest `ArcStats` struct; raw map omitted from the wire to
 * keep responses small.
 */
export type ArcStats = {
    size: number;
    c: number;
    c_min: number;
    c_max: number;
    hits: number;
    misses: number;
    demand_data_hits: number;
    demand_data_misses: number;
    demand_metadata_hits: number;
    demand_metadata_misses: number;
    prefetch_data_hits: number;
    prefetch_data_misses: number;
    prefetch_metadata_hits: number;
    prefetch_metadata_misses: number;
    mru_hits: number;
    mfu_hits: number;
    mru_ghost_hits: number;
    mfu_ghost_hits: number;
    l2_size: number;
    l2_hits: number;
    l2_misses: number;
    compressed_size: number;
    uncompressed_size: number;
    /**
     * `hits / (hits + misses)`, `None` when the cache has had no
     * traffic yet (avoids leaking JSON `NaN`).
     */
    hit_ratio?: number | null;
};

/**
 * Body of `GET /api/v1/config` — the on-disk TOML the daemon was
 * started with, plus its absolute path. Read-only: there is no
 * write-back endpoint, so this is a faithful echo of what's loaded,
 * not what the daemon may have parsed (you can spot drift by
 * comparing to the other endpoints).
 */
export type ConfigView = {
    path: string;
    content_toml: string;
};

/**
 * Body of `POST /api/v1/datasets/{name}/snapshots/{snapshot}/holds`.
 * `arctern_*` tags are reserved for the replication machinery and
 * rejected.
 */
export type CreateHoldRequest = {
    tag: string;
};

/**
 * Request body for `POST /api/v1/datasets/{name}/snapshots`. The path
 * segment carries the parent dataset; this struct carries everything
 * else. `recursive` and `properties` default so a minimal client can
 * post `{"snapshot_name":"…"}` and get the common case.
 */
export type CreateSnapshotRequest = {
    snapshot_name: string;
    recursive?: boolean;
    properties?: {
        [key: string]: string;
    };
};

/**
 * Slim projection of [`palimpsest::ZfsListEntry`] suitable for HTTP +
 * OpenAPI. Native ZFS properties carry typed data (bytes, bool, …) but
 * `BTreeMap<String, String>` serializes more cleanly through utoipa;
 * consumers parse property values as needed.
 */
export type DatasetSummary = {
    name: string;
    /**
     * `"filesystem" | "volume" | "snapshot" | "bookmark"` — lowercase
     * to match `zfs(8)`'s output and avoid leaking palimpsest's enum repr.
     */
    dataset_type: string;
    properties?: {
        [key: string]: string;
    };
};

/**
 * One row of `job_runs` returned by `GET /api/v1/jobs/{name}/runs`.
 * `started_at` / `finished_at` are unix seconds; `bytes_sent` is set
 * only by push jobs that finished cleanly.
 */
export type JobRun = {
    started_at: number;
    finished_at?: number | null;
    status: string;
    error_message?: string | null;
    bytes_sent?: number | null;
};

/**
 * One entry in the response of `GET /api/v1/jobs`. RFC3339 timestamps
 * are nullable: `last_run` is null until the job has completed at
 * least one cycle; `next_run` is set as soon as the loop knows when
 * it will fire next; `last_error` is null when the most recent cycle
 * finished cleanly.
 */
export type JobStatus = {
    name: string;
    kind: string;
    last_run?: string | null;
    next_run?: string | null;
    last_error?: string | null;
    /**
     * True while a cycle is currently executing (e.g. a multi-hour
     * full send). `last_*` fields describe the previous cycle.
     */
    running?: boolean;
    /**
     * True while the job is paused: the current transfer was aborted
     * (resumably) and scheduled cycles are suspended until resumed.
     */
    paused?: boolean;
    transfer?: null | TransferInfo;
    /**
     * Push jobs: per-target replication policy + last outcome.
     * Empty for snap/prune jobs.
     */
    targets?: Array<TargetStatus>;
};

/**
 * One row in `GET /api/v1/events` (and the proxied
 * `GET /api/v1/peers/{peer}/events`). Mirrors
 * `arctern_transport::EventWire` but lives in the public API surface
 * so clients don't pull in the transport crate.
 */
export type LogEvent = {
    id: number;
    /**
     * Unix seconds.
     */
    timestamp: number;
    level: string;
    job_name?: string | null;
    message: string;
};

/**
 * Reachability classification for one configured peer. The daemon
 * updates this from its background reconnect loop; the UI surfaces
 * it in the Peers tab.
 */
export type PeerReachability = {
    kind: 'connected';
} | {
    /**
     * RFC3339 timestamp the link first went down.
     */
    since: string;
    kind: 'reconnecting';
} | {
    /**
     * RFC3339 timestamp the link first went down (or last failed).
     */
    since: string;
    last_error: string;
    kind: 'failed';
};

/**
 * One network route of a peer, in priority order (first = preferred).
 */
export type PeerRoute = {
    name: string;
    ssh_target: string;
    /**
     * Whether scheduled (auto) replication may run over this route.
     */
    auto: boolean;
    /**
     * `"connected" | "failed" | "unknown"` — last connect result for
     * this route. Lower-priority routes are only probed on failover /
     * re-rank, so `unknown` is the common idle state.
     */
    health: string;
    last_error?: string | null;
    /**
     * RFC3339 timestamp of the last connect attempt, if any.
     */
    last_checked?: string | null;
};

/**
 * One snapshot returned by `GET /api/v1/peers/{peer}/snapshots`.
 */
export type PeerSnapshotEntry = {
    name: string;
    /**
     * ZFS GUID, serialized as a u64 string to stay safe across
     * JSON parsers that downgrade large integers to f64.
     */
    guid: string;
    createtxg: number;
    /**
     * `creation` property, unix seconds (None from peers predating it).
     */
    creation?: number | null;
    /**
     * `used` property, bytes.
     */
    used?: number | null;
};

/**
 * One row in `GET /api/v1/peers`.
 */
export type PeerSummary = {
    name: string;
    reachability: PeerReachability;
    /**
     * Name of the route the live link currently runs over.
     */
    active_route?: string | null;
    routes: Array<PeerRoute>;
};

/**
 * `GET /api/v1/pools/{name}` — full status: scrub + recursive vdev tree.
 */
export type PoolStatus = {
    name: string;
    state: string;
    error_count: string;
    pool_guid: string;
    txg: string;
    scan?: null | ScanSummary;
    vdevs: Array<VdevNode>;
};

/**
 * One pool's slot in `GET /api/v1/pools`. Numeric fields are
 * `zpool`-formatted strings (e.g. `"608G"`, `"1.48T"`) rather than
 * raw bytes because that's what `zpool` emits and round-tripping
 * through bytes risks rounding mismatches in the UI.
 */
export type PoolSummary = {
    name: string;
    /**
     * `"ONLINE"`, `"DEGRADED"`, `"FAULTED"`, …
     */
    state: string;
    /**
     * Aggregate error count across all vdevs.
     */
    error_count: string;
    alloc_space: string;
    total_space: string;
    scan?: null | ScanSummary;
};

export type ScanSummary = {
    /**
     * `"SCRUB"`, `"RESILVER"`, `"NONE"`.
     */
    function: string;
    /**
     * `"SCANNING"`, `"FINISHED"`, `"CANCELED"`.
     */
    state: string;
    start_time?: string | null;
    end_time?: string | null;
    to_examine?: string | null;
    examined?: string | null;
    errors?: string | null;
    pass_start?: string | null;
    scrub_pause?: string | null;
    issued?: string | null;
};

/**
 * Body of `POST /api/v1/pools/{name}/scrub`.
 */
export type ScrubRequest = {
    /**
     * `"start"`, `"pause"`, `"resume"`, or `"stop"`.
     */
    action: string;
};

/**
 * One hold entry returned by
 * `GET /api/v1/datasets/{name}/snapshots/{snapshot}/holds`.
 * `timestamp` is unix seconds.
 */
export type SnapshotHold = {
    tag: string;
    timestamp: number;
};

/**
 * One replication target of a push job.
 */
export type TargetStatus = {
    peer: string;
    /**
     * `"auto" | "manual"`.
     */
    mode: string;
    connected: boolean;
    /**
     * Active route name while connected (e.g. `"lan"`).
     */
    route?: string | null;
    /**
     * Whether the active route permits scheduled replication.
     */
    route_auto?: boolean;
    /**
     * For auto mode: the configured `auto_interval` in seconds. The
     * next auto sync is `last_success + auto_interval_secs` (or the
     * next planner tick when unset/no history).
     */
    auto_interval_secs?: number | null;
    /**
     * Unix seconds of the last successful sync to this peer.
     */
    last_success?: number | null;
    last_error?: string | null;
};

/**
 * Progress of an in-flight `zfs send` stream.
 */
export type TransferInfo = {
    dataset: string;
    peer: string;
    /**
     * `"full" | "incremental" | "resume"`.
     */
    kind: string;
    bytes_sent: number;
    /**
     * Dry-run estimate. None for resume sends (no estimate available).
     */
    total_bytes?: number | null;
    /**
     * Unix seconds.
     */
    started_at: number;
};

/**
 * Recursive vdev tree as a flat list of trees. Wire-friendlier than
 * palimpsest's map<name, VdevStatus> for UIs that want to render in
 * declared order.
 *
 * `children` carries the `#[schema(no_recursion)]` attribute so
 * utoipa's auto-collector stops at the cycle and emits a `$ref` to
 * `VdevNode` itself instead of inlining the type — without this
 * `ApiDoc::openapi()` infinite-recurses and overflows the stack at
 * startup. See utoipa docs on recursive schemas.
 */
export type VdevNode = {
    name: string;
    vdev_type: string;
    state: string;
    alloc_space: string;
    total_space: string;
    read_errors: string;
    write_errors: string;
    checksum_errors: string;
    path?: string | null;
    children: Array<VdevNode>;
};

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config';
};

export type GetConfigErrors = {
    /**
     * Config file unreadable
     */
    500: ApiErrorBody;
};

export type GetConfigError = GetConfigErrors[keyof GetConfigErrors];

export type GetConfigResponses = {
    /**
     * The TOML file currently loaded
     */
    200: ConfigView;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type ListDatasetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/datasets';
};

export type ListDatasetsErrors = {
    /**
     * ZFS returned an error
     */
    500: ApiErrorBody;
};

export type ListDatasetsError = ListDatasetsErrors[keyof ListDatasetsErrors];

export type ListDatasetsResponses = {
    /**
     * All datasets visible to the daemon's ZFS runner
     */
    200: Array<DatasetSummary>;
};

export type ListDatasetsResponse = ListDatasetsResponses[keyof ListDatasetsResponses];

export type ListSnapshotsData = {
    body?: never;
    path: {
        /**
         * Parent dataset (URL-encode `/` as %2F)
         */
        name: string;
    };
    query?: {
        /**
         * Filter to snapshots whose tag (after the `@`) starts with this
         * prefix. Useful to keep zrepl_-style snapshots out of the noise
         * when manual snapshots also exist on the dataset.
         */
        prefix?: string | null;
    };
    url: '/api/v1/datasets/{name}/snapshots';
};

export type ListSnapshotsErrors = {
    /**
     * Dataset not found
     */
    404: ApiErrorBody;
    /**
     * ZFS returned an error
     */
    500: ApiErrorBody;
};

export type ListSnapshotsError = ListSnapshotsErrors[keyof ListSnapshotsErrors];

export type ListSnapshotsResponses = {
    /**
     * Snapshots of the dataset, oldest first
     */
    200: Array<DatasetSummary>;
};

export type ListSnapshotsResponse = ListSnapshotsResponses[keyof ListSnapshotsResponses];

export type CreateSnapshotData = {
    body: CreateSnapshotRequest;
    path: {
        /**
         * Parent dataset (URL-encode `/` as %2F)
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/datasets/{name}/snapshots';
};

export type CreateSnapshotErrors = {
    /**
     * Parent dataset not found
     */
    404: ApiErrorBody;
    /**
     * Snapshot already exists
     */
    409: ApiErrorBody;
    /**
     * ZFS returned an error
     */
    500: ApiErrorBody;
};

export type CreateSnapshotError = CreateSnapshotErrors[keyof CreateSnapshotErrors];

export type CreateSnapshotResponses = {
    /**
     * Snapshot created
     */
    201: DatasetSummary;
};

export type CreateSnapshotResponse = CreateSnapshotResponses[keyof CreateSnapshotResponses];

export type DestroySnapshotData = {
    body?: never;
    path: {
        /**
         * Parent dataset (URL-encode `/` as %2F)
         */
        name: string;
        /**
         * Snapshot tag (the part after `@`)
         */
        snapshot: string;
    };
    query?: never;
    url: '/api/v1/datasets/{name}/snapshots/{snapshot}/destroy';
};

export type DestroySnapshotErrors = {
    /**
     * Snapshot not found
     */
    404: ApiErrorBody;
    /**
     * Snapshot has a hold
     */
    409: ApiErrorBody;
    /**
     * ZFS returned an error
     */
    500: ApiErrorBody;
};

export type DestroySnapshotError = DestroySnapshotErrors[keyof DestroySnapshotErrors];

export type DestroySnapshotResponses = {
    /**
     * Snapshot destroyed
     */
    204: void;
};

export type DestroySnapshotResponse = DestroySnapshotResponses[keyof DestroySnapshotResponses];

export type ListHoldsData = {
    body?: never;
    path: {
        /**
         * Parent dataset (URL-encode `/` as %2F)
         */
        name: string;
        /**
         * Snapshot tag (the part after `@`)
         */
        snapshot: string;
    };
    query?: never;
    url: '/api/v1/datasets/{name}/snapshots/{snapshot}/holds';
};

export type ListHoldsErrors = {
    /**
     * Snapshot not found
     */
    404: ApiErrorBody;
    /**
     * ZFS returned an error
     */
    500: ApiErrorBody;
};

export type ListHoldsError = ListHoldsErrors[keyof ListHoldsErrors];

export type ListHoldsResponses = {
    /**
     * Holds on the snapshot, oldest first
     */
    200: Array<SnapshotHold>;
};

export type ListHoldsResponse = ListHoldsResponses[keyof ListHoldsResponses];

export type CreateHoldData = {
    body: CreateHoldRequest;
    path: {
        /**
         * Parent dataset (URL-encode `/` as %2F)
         */
        name: string;
        /**
         * Snapshot tag (the part after `@`)
         */
        snapshot: string;
    };
    query?: never;
    url: '/api/v1/datasets/{name}/snapshots/{snapshot}/holds';
};

export type CreateHoldErrors = {
    /**
     * Invalid or reserved tag
     */
    400: ApiErrorBody;
    /**
     * Snapshot not found
     */
    404: ApiErrorBody;
    /**
     * ZFS returned an error
     */
    500: ApiErrorBody;
};

export type CreateHoldError = CreateHoldErrors[keyof CreateHoldErrors];

export type CreateHoldResponses = {
    /**
     * Hold placed
     */
    201: unknown;
};

export type ReleaseHoldData = {
    body?: never;
    path: {
        /**
         * Parent dataset (URL-encode `/` as %2F)
         */
        name: string;
        /**
         * Snapshot tag (the part after `@`)
         */
        snapshot: string;
        /**
         * Hold tag to release
         */
        tag: string;
    };
    query?: never;
    url: '/api/v1/datasets/{name}/snapshots/{snapshot}/holds/{tag}';
};

export type ReleaseHoldErrors = {
    /**
     * Snapshot or hold not found
     */
    404: ApiErrorBody;
    /**
     * ZFS returned an error
     */
    500: ApiErrorBody;
};

export type ReleaseHoldError = ReleaseHoldErrors[keyof ReleaseHoldErrors];

export type ReleaseHoldResponses = {
    /**
     * Hold released
     */
    204: void;
};

export type ReleaseHoldResponse = ReleaseHoldResponses[keyof ReleaseHoldResponses];

export type StreamEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events';
};

export type StreamEventsResponses = {
    /**
     * SSE stream of LogEvent JSON frames
     */
    200: unknown;
};

export type RecentEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum rows, newest kept, returned oldest-first. Default 100.
         */
        limit?: number | null;
    };
    url: '/api/v1/events/recent';
};

export type RecentEventsResponses = {
    /**
     * Most recent log events, oldest first
     */
    200: Array<LogEvent>;
};

export type RecentEventsResponse = RecentEventsResponses[keyof RecentEventsResponses];

export type ListJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/jobs';
};

export type ListJobsResponses = {
    /**
     * Per-job status snapshot
     */
    200: Array<JobStatus>;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type CancelData = {
    body?: never;
    path: {
        /**
         * Job name
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/jobs/{name}/cancel';
};

export type CancelErrors = {
    /**
     * No such job
     */
    404: unknown;
    /**
     * Job kind does not support cancel
     */
    409: unknown;
};

export type CancelResponses = {
    /**
     * In-flight transfer aborted (partial recv state on the receiver keeps it resumable)
     */
    204: void;
};

export type CancelResponse = CancelResponses[keyof CancelResponses];

export type PauseData = {
    body?: never;
    path: {
        /**
         * Job name
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/jobs/{name}/pause';
};

export type PauseErrors = {
    /**
     * No such job
     */
    404: unknown;
    /**
     * Job kind does not support pause
     */
    409: unknown;
};

export type PauseResponses = {
    /**
     * Transfer aborted resumably; scheduled cycles suspended
     */
    204: void;
};

export type PauseResponse = PauseResponses[keyof PauseResponses];

export type PushToPeerData = {
    body?: never;
    path: {
        /**
         * Job name
         */
        name: string;
        /**
         * Target peer name from the job's targets
         */
        peer: string;
    };
    query?: never;
    url: '/api/v1/jobs/{name}/push/{peer}';
};

export type PushToPeerErrors = {
    /**
     * Peer is not a target of this job
     */
    400: ApiErrorBody;
    /**
     * No such job
     */
    404: unknown;
};

export type PushToPeerError = PushToPeerErrors[keyof PushToPeerErrors];

export type PushToPeerResponses = {
    /**
     * Manual replication to the peer queued
     */
    204: void;
};

export type PushToPeerResponse = PushToPeerResponses[keyof PushToPeerResponses];

export type ResumeData = {
    body?: never;
    path: {
        /**
         * Job name
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/jobs/{name}/resume';
};

export type ResumeErrors = {
    /**
     * No such job
     */
    404: unknown;
    /**
     * Job kind does not support resume
     */
    409: unknown;
};

export type ResumeResponses = {
    /**
     * Job unpaused; the next cycle resumes the partial transfer
     */
    204: void;
};

export type ResumeResponse = ResumeResponses[keyof ResumeResponses];

export type ListRunsData = {
    body?: never;
    path: {
        /**
         * Job name as declared in arctern.toml
         */
        name: string;
    };
    query?: {
        /**
         * Unix-second cutoff; rows with `started_at >= since` are returned.
         */
        since?: number | null;
        /**
         * Maximum number of rows to return. Defaults to 100, capped at 1000.
         */
        limit?: number | null;
    };
    url: '/api/v1/jobs/{name}/runs';
};

export type ListRunsResponses = {
    /**
     * Recent job runs, newest first
     */
    200: Array<JobRun>;
};

export type ListRunsResponse = ListRunsResponses[keyof ListRunsResponses];

export type WakeupData = {
    body?: never;
    path: {
        /**
         * Job name as declared in arctern.toml
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/jobs/{name}/wakeup';
};

export type WakeupErrors = {
    /**
     * No job with that name is registered
     */
    404: unknown;
};

export type WakeupResponses = {
    /**
     * Job's cycle loop was woken up
     */
    204: void;
};

export type WakeupResponse = WakeupResponses[keyof WakeupResponses];

export type ListPeersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/peers';
};

export type ListPeersResponses = {
    /**
     * Configured peers with reachability
     */
    200: Array<PeerSummary>;
};

export type ListPeersResponse = ListPeersResponses[keyof ListPeersResponses];

export type ListPeerDatasetsData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/datasets';
};

export type ListPeerDatasetsErrors = {
    /**
     * No such peer
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type ListPeerDatasetsError = ListPeerDatasetsErrors[keyof ListPeerDatasetsErrors];

export type ListPeerDatasetsResponses = {
    /**
     * Receiver datasets under the client's allowed root_fs
     */
    200: Array<DatasetSummary>;
};

export type ListPeerDatasetsResponse = ListPeerDatasetsResponses[keyof ListPeerDatasetsResponses];

export type ListPeerSnapshotHoldsData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
        /**
         * Dataset on the peer (URL-encode `/` as %2F)
         */
        name: string;
        /**
         * Snapshot tag (the part after `@`)
         */
        snapshot: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/datasets/{name}/snapshots/{snapshot}/holds';
};

export type ListPeerSnapshotHoldsErrors = {
    /**
     * No such peer / snapshot
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type ListPeerSnapshotHoldsError = ListPeerSnapshotHoldsErrors[keyof ListPeerSnapshotHoldsErrors];

export type ListPeerSnapshotHoldsResponses = {
    /**
     * Holds on the peer's snapshot, oldest first
     */
    200: Array<SnapshotHold>;
};

export type ListPeerSnapshotHoldsResponse = ListPeerSnapshotHoldsResponses[keyof ListPeerSnapshotHoldsResponses];

export type StreamPeerEventsData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/events';
};

export type StreamPeerEventsErrors = {
    /**
     * No such peer
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type StreamPeerEventsError = StreamPeerEventsErrors[keyof StreamPeerEventsErrors];

export type StreamPeerEventsResponses = {
    /**
     * SSE stream of LogEvent JSON frames from the peer
     */
    200: unknown;
};

export type ListPeerJobsData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/jobs';
};

export type ListPeerJobsErrors = {
    /**
     * No such peer
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type ListPeerJobsError = ListPeerJobsErrors[keyof ListPeerJobsErrors];

export type ListPeerJobsResponses = {
    /**
     * Per-job status snapshot from the peer
     */
    200: Array<JobStatus>;
};

export type ListPeerJobsResponse = ListPeerJobsResponses[keyof ListPeerJobsResponses];

export type GetPeerJobData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
        /**
         * Job name on the peer
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/jobs/{name}';
};

export type GetPeerJobErrors = {
    /**
     * No such peer / job
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type GetPeerJobError = GetPeerJobErrors[keyof GetPeerJobErrors];

export type GetPeerJobResponses = {
    /**
     * Status for one job on the peer
     */
    200: JobStatus;
};

export type GetPeerJobResponse = GetPeerJobResponses[keyof GetPeerJobResponses];

export type WakeupPeerJobData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
        /**
         * Job name on the peer
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/jobs/{name}/wakeup';
};

export type WakeupPeerJobErrors = {
    /**
     * No such peer / job
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type WakeupPeerJobError = WakeupPeerJobErrors[keyof WakeupPeerJobErrors];

export type WakeupPeerJobResponses = {
    /**
     * Wakeup delivered
     */
    204: void;
};

export type WakeupPeerJobResponse = WakeupPeerJobResponses[keyof WakeupPeerJobResponses];

export type ListPeerSnapshotsData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
    };
    query: {
        /**
         * Dataset on the peer
         */
        dataset: string;
        /**
         * Optional name filter
         */
        prefix_regex?: string;
    };
    url: '/api/v1/peers/{peer}/snapshots';
};

export type ListPeerSnapshotsErrors = {
    /**
     * No such peer / dataset
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type ListPeerSnapshotsError = ListPeerSnapshotsErrors[keyof ListPeerSnapshotsErrors];

export type ListPeerSnapshotsResponses = {
    /**
     * Snapshots on the peer for the dataset
     */
    200: Array<PeerSnapshotEntry>;
};

export type ListPeerSnapshotsResponse = ListPeerSnapshotsResponses[keyof ListPeerSnapshotsResponses];

export type DestroyPeerSnapshotData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
        /**
         * Snapshot name (URL-encode @ and /)
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/snapshots/{name}/destroy';
};

export type DestroyPeerSnapshotErrors = {
    /**
     * Not allowed under the peer's ACL
     */
    403: ApiErrorBody;
    /**
     * No such peer / snapshot
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type DestroyPeerSnapshotError = DestroyPeerSnapshotErrors[keyof DestroyPeerSnapshotErrors];

export type DestroyPeerSnapshotResponses = {
    /**
     * Snapshot destroyed on the peer
     */
    204: void;
};

export type DestroyPeerSnapshotResponse = DestroyPeerSnapshotResponses[keyof DestroyPeerSnapshotResponses];

export type ListPoolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/pools';
};

export type ListPoolsErrors = {
    /**
     * zpool returned an error
     */
    500: ApiErrorBody;
};

export type ListPoolsError = ListPoolsErrors[keyof ListPoolsErrors];

export type ListPoolsResponses = {
    /**
     * All imported pools with health + capacity
     */
    200: Array<PoolSummary>;
};

export type ListPoolsResponse = ListPoolsResponses[keyof ListPoolsResponses];

export type GetPoolData = {
    body?: never;
    path: {
        /**
         * Pool name
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/pools/{name}';
};

export type GetPoolErrors = {
    /**
     * No imported pool with that name
     */
    404: ApiErrorBody;
    /**
     * zpool returned an error
     */
    500: ApiErrorBody;
};

export type GetPoolError = GetPoolErrors[keyof GetPoolErrors];

export type GetPoolResponses = {
    /**
     * Full status with vdev tree + scrub progress
     */
    200: PoolStatus;
};

export type GetPoolResponse = GetPoolResponses[keyof GetPoolResponses];

export type PoolScrubData = {
    body: ScrubRequest;
    path: {
        /**
         * Pool name
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/pools/{name}/scrub';
};

export type PoolScrubErrors = {
    /**
     * Unknown action
     */
    400: ApiErrorBody;
    /**
     * zpool returned an error
     */
    500: ApiErrorBody;
};

export type PoolScrubError = PoolScrubErrors[keyof PoolScrubErrors];

export type PoolScrubResponses = {
    /**
     * zpool scrub accepted the action
     */
    204: void;
};

export type PoolScrubResponse = PoolScrubResponses[keyof PoolScrubResponses];

export type GetArcData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/arc';
};

export type GetArcErrors = {
    /**
     * Could not read /proc/spl/kstat/zfs/arcstats
     */
    500: ApiErrorBody;
};

export type GetArcError = GetArcErrors[keyof GetArcErrors];

export type GetArcResponses = {
    /**
     * Current ARC stats snapshot
     */
    200: ArcStats;
};

export type GetArcResponse = GetArcResponses[keyof GetArcResponses];

export type GetArcHistoryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Unix-second cutoff; rows with `timestamp >= since` are returned.
         */
        since?: number | null;
        /**
         * Maximum rows to return. Default 1440 (24h at 1m resolution).
         */
        limit?: number | null;
    };
    url: '/api/v1/system/arc/history';
};

export type GetArcHistoryResponses = {
    /**
     * Recent ARC samples, newest first
     */
    200: Array<ArcHistoryPoint>;
};

export type GetArcHistoryResponse = GetArcHistoryResponses[keyof GetArcHistoryResponses];
