// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body shape for `4xx`/`5xx` responses from the daemon. `error` is a
 * short machine-readable category (`spawn`, `dataset_not_found`, …);
 * `message` is a human-readable description.
 */
export type ApiErrorBody = {
    error: string;
    message: string;
};

/**
 * Request body for `POST /api/v1/datasets/{name}/snapshots`. The path
 * segment carries the parent dataset; this struct carries everything
 * else. `recursive` and `properties` default so a minimal client can
 * post `{"snapshot_name":"…"}` and get the common case.
 */
export type CreateSnapshotRequest = {
    snapshot_name: string;
    recursive?: boolean;
    properties?: {
        [key: string]: string;
    };
};

/**
 * Slim projection of [`palimpsest::ZfsListEntry`] suitable for HTTP +
 * OpenAPI. Native ZFS properties carry typed data (bytes, bool, …) but
 * `BTreeMap<String, String>` serializes more cleanly through utoipa;
 * consumers parse property values as needed.
 */
export type DatasetSummary = {
    name: string;
    /**
     * `"filesystem" | "volume" | "snapshot" | "bookmark"` — lowercase
     * to match `zfs(8)`'s output and avoid leaking palimpsest's enum repr.
     */
    dataset_type: string;
    properties?: {
        [key: string]: string;
    };
};

/**
 * One entry in the response of `GET /api/v1/jobs`. RFC3339 timestamps
 * are nullable: `last_run` is null until the job has completed at
 * least one cycle; `next_run` is set as soon as the loop knows when
 * it will fire next; `last_error` is null when the most recent cycle
 * finished cleanly.
 */
export type JobStatus = {
    name: string;
    kind: string;
    last_run?: string | null;
    next_run?: string | null;
    last_error?: string | null;
};

/**
 * One row in `GET /api/v1/events` (and the proxied
 * `GET /api/v1/peers/{peer}/events`). Mirrors
 * `arctern_transport::EventWire` but lives in the public API surface
 * so clients don't pull in the transport crate.
 */
export type LogEvent = {
    id: number;
    /**
     * Unix seconds.
     */
    timestamp: number;
    level: string;
    job_name?: string | null;
    message: string;
};

/**
 * Reachability classification for one configured peer. The daemon
 * updates this from its background reconnect loop; the UI surfaces
 * it in the Peers tab.
 */
export type PeerReachability = {
    kind: 'connected';
} | {
    /**
     * RFC3339 timestamp the link first went down.
     */
    since: string;
    kind: 'reconnecting';
} | {
    /**
     * RFC3339 timestamp the link first went down (or last failed).
     */
    since: string;
    last_error: string;
    kind: 'failed';
};

/**
 * One snapshot returned by `GET /api/v1/peers/{peer}/snapshots`.
 */
export type PeerSnapshotEntry = {
    name: string;
    /**
     * ZFS GUID, serialized as a u64 string to stay safe across
     * JSON parsers that downgrade large integers to f64.
     */
    guid: string;
    createtxg: number;
};

/**
 * One row in `GET /api/v1/peers`.
 */
export type PeerSummary = {
    name: string;
    ssh_target: string;
    reachability: PeerReachability;
};

export type ListDatasetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/datasets';
};

export type ListDatasetsErrors = {
    /**
     * ZFS returned an error
     */
    500: ApiErrorBody;
    /**
     * Could not spawn the underlying zfs subprocess
     */
    503: ApiErrorBody;
};

export type ListDatasetsError = ListDatasetsErrors[keyof ListDatasetsErrors];

export type ListDatasetsResponses = {
    /**
     * All datasets visible to the daemon's ZFS runner
     */
    200: Array<DatasetSummary>;
};

export type ListDatasetsResponse = ListDatasetsResponses[keyof ListDatasetsResponses];

export type CreateSnapshotData = {
    body: CreateSnapshotRequest;
    path: {
        /**
         * Parent dataset (URL-encode `/` as %2F)
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/datasets/{name}/snapshots';
};

export type CreateSnapshotErrors = {
    /**
     * Parent dataset not found
     */
    404: ApiErrorBody;
    /**
     * Snapshot already exists
     */
    409: ApiErrorBody;
    /**
     * ZFS returned an error
     */
    500: ApiErrorBody;
    /**
     * Could not spawn the underlying zfs subprocess
     */
    503: ApiErrorBody;
};

export type CreateSnapshotError = CreateSnapshotErrors[keyof CreateSnapshotErrors];

export type CreateSnapshotResponses = {
    /**
     * Snapshot created
     */
    201: DatasetSummary;
};

export type CreateSnapshotResponse = CreateSnapshotResponses[keyof CreateSnapshotResponses];

export type StreamEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events';
};

export type StreamEventsResponses = {
    /**
     * SSE stream of LogEvent JSON frames
     */
    200: unknown;
};

export type ListJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/jobs';
};

export type ListJobsResponses = {
    /**
     * Per-job status snapshot
     */
    200: Array<JobStatus>;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type WakeupData = {
    body?: never;
    path: {
        /**
         * Job name as declared in arctern.toml
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/jobs/{name}/wakeup';
};

export type WakeupErrors = {
    /**
     * No job with that name is registered
     */
    404: unknown;
};

export type WakeupResponses = {
    /**
     * Job's cycle loop was woken up
     */
    204: void;
};

export type WakeupResponse = WakeupResponses[keyof WakeupResponses];

export type ListPeersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/peers';
};

export type ListPeersResponses = {
    /**
     * Configured peers with reachability
     */
    200: Array<PeerSummary>;
};

export type ListPeersResponse = ListPeersResponses[keyof ListPeersResponses];

export type StreamPeerEventsData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/events';
};

export type StreamPeerEventsErrors = {
    /**
     * No such peer
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type StreamPeerEventsError = StreamPeerEventsErrors[keyof StreamPeerEventsErrors];

export type StreamPeerEventsResponses = {
    /**
     * SSE stream of LogEvent JSON frames from the peer
     */
    200: unknown;
};

export type ListPeerJobsData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/jobs';
};

export type ListPeerJobsErrors = {
    /**
     * No such peer
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type ListPeerJobsError = ListPeerJobsErrors[keyof ListPeerJobsErrors];

export type ListPeerJobsResponses = {
    /**
     * Per-job status snapshot from the peer
     */
    200: Array<JobStatus>;
};

export type ListPeerJobsResponse = ListPeerJobsResponses[keyof ListPeerJobsResponses];

export type GetPeerJobData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
        /**
         * Job name on the peer
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/jobs/{name}';
};

export type GetPeerJobErrors = {
    /**
     * No such peer / job
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type GetPeerJobError = GetPeerJobErrors[keyof GetPeerJobErrors];

export type GetPeerJobResponses = {
    /**
     * Status for one job on the peer
     */
    200: JobStatus;
};

export type GetPeerJobResponse = GetPeerJobResponses[keyof GetPeerJobResponses];

export type WakeupPeerJobData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
        /**
         * Job name on the peer
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/jobs/{name}/wakeup';
};

export type WakeupPeerJobErrors = {
    /**
     * No such peer / job
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type WakeupPeerJobError = WakeupPeerJobErrors[keyof WakeupPeerJobErrors];

export type WakeupPeerJobResponses = {
    /**
     * Wakeup delivered
     */
    204: void;
};

export type WakeupPeerJobResponse = WakeupPeerJobResponses[keyof WakeupPeerJobResponses];

export type ListPeerSnapshotsData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
    };
    query: {
        /**
         * Dataset on the peer
         */
        dataset: string;
        /**
         * Optional name filter
         */
        prefix_regex?: string;
    };
    url: '/api/v1/peers/{peer}/snapshots';
};

export type ListPeerSnapshotsErrors = {
    /**
     * No such peer / dataset
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type ListPeerSnapshotsError = ListPeerSnapshotsErrors[keyof ListPeerSnapshotsErrors];

export type ListPeerSnapshotsResponses = {
    /**
     * Snapshots on the peer for the dataset
     */
    200: Array<PeerSnapshotEntry>;
};

export type ListPeerSnapshotsResponse = ListPeerSnapshotsResponses[keyof ListPeerSnapshotsResponses];

export type DestroyPeerSnapshotData = {
    body?: never;
    path: {
        /**
         * Peer name from [[peers]]
         */
        peer: string;
        /**
         * Snapshot name (URL-encode @ and /)
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/peers/{peer}/snapshots/{name}/destroy';
};

export type DestroyPeerSnapshotErrors = {
    /**
     * Not allowed under the peer's ACL
     */
    403: ApiErrorBody;
    /**
     * No such peer / snapshot
     */
    404: ApiErrorBody;
    /**
     * Peer not currently connected
     */
    503: ApiErrorBody;
};

export type DestroyPeerSnapshotError = DestroyPeerSnapshotErrors[keyof DestroyPeerSnapshotErrors];

export type DestroyPeerSnapshotResponses = {
    /**
     * Snapshot destroyed on the peer
     */
    204: void;
};

export type DestroyPeerSnapshotResponse = DestroyPeerSnapshotResponses[keyof DestroyPeerSnapshotResponses];
